### ISSUE TITLE
English dataset?

### ISSUE THREAD

**Issue by juhonkang** [SineStriker/qsynthesis-revenge#13]
Hi, can the MinLabel be used for English or other languages datasets?

**Comment by yqzhishen** [comment]
Hello, there are no standard English dictionary and MFA model (and training data of it) yet. If you have any ideas, feel free to start a discussion at [DiffSinger](https://github.com/openvpi/DiffSinger/discussions) or [MakeDiffSinger](https://github.com/openvpi/MakeDiffSinger/discussions).

**Comment by SineStriker** [comment]
The tools has been migrated to [OpenVPI/dataset-tools](https://github.com/openvpi/dataset-tools), so I'll close it now.
